### ISSUE TITLE
Controlling state - page and filter problem

### ISSUE THREAD

**Issue by gustavorino** [tannerlinsley/react-table#401] opened 2017-07-25 21:16 UTC
I've found a small thing here :

Example : https://codepen.io/anon/pen/ayzKoO

- Navigate to the last page.
- Type "tiger" on FirstName filter -> no results, 
- Go back to the first page and you will see a "Tiger" record

Shouldn't ReactTable internally clamp the "page" prop to the maximum available page on that case?

I know that I could reset to page 0 when some filter changes, but that doesn't seem the best solution.

Thanks for this amazing component.

**Comment by tannerlinsley** [comment] 2017-07-31 14:47
This is a duplicate of #273, tracking there.

**Closed by tannerlinsley** 2017-07-31 14:47 UTC
