### ISSUE TITLE
StrictMode

### ISSUE THREAD

**Issue by armin2200** [tannerlinsley/react-table#2387] opened 2020-05-29 05:53 UTC
**Describe the bug (required)**
if Wrapping App with React.StrictMode , when you use useRowSelect , checkboxes doesn’t work correctly 
<React.StrictMode>
    <App />
  </React.StrictMode>

https://ndh6t.csb.app/

**Comment by maxime4000** [comment] 2020-07-23 18:45
I did report the same issues with example. Each refresh of the table can allow one select/unselect and after it's done until a new refresh of the data. Kinda weird... The select all always work while select one is broken...
I made a duplicate of this issues here : https://github.com/tannerlinsley/react-table/issues/2566

**Comment by tannerlinsley** [comment] 2020-08-03 18:13
Let's track there.

**Closed by tannerlinsley** 2020-08-03 18:13 UTC
