### ISSUE TITLE
filtering doesn't filter subRows data

### ISSUE THREAD

**Issue by kenjoegolo** [tannerlinsley/react-table#1673] opened 2019-12-01 15:14 UTC
# Using v6?
No

# Using v7?
Yes - `react-table@7.0.0-beta.14`

**Describe the bug**
Filtering is not working on subRows.

**To Reproduce**
Sample codesandbox here:
https://codesandbox.io/s/condescending-fog-jfo6o

**Comment by tannerlinsley** [comment] 2019-12-01 16:43
- Upgrade to the latest beta
- filter the name column to “Doe”
- notice that both the first row and its child are still there
- filter to “Jane”
- you’ll see that the first row does not match Jane and is removed along with its child row

**Comment by tannerlinsley** [comment] 2019-12-01 16:46
If that’s not the functionality you expect then I’ll need more info I on what it is you want to happen. Thus far, everything is working as expected. It’s important to know that if a row is filtered out, then all of its sub rows will be as well.

**Comment by kenjoegolo** [comment] 2019-12-02 09:16
Thanks for the quick response, sorry, I was expecting the parent row will be display if the search filter is equal to one of its child.
e.g: 

- filter the name column to "Rita"
- Row with name "Jane Doe" should display with its subRows

Maybe I will not use filtering for this case, I'm thinking of creating custom filtering then rerender the table.

**Comment by tannerlinsley** [comment] 2019-12-02 16:44
I see. This is an interesting approach. Almost like you want to treat the parent rows as if they are not a part of the data model? The way you are describing it almost sounds like a groupBy data model instead of a sub row model. Grouped rows create meta rows which really just reflect the filtered state of the rows they contain. Thoughts?

**Comment by tannerlinsley** [comment] 2019-12-02 16:50
Closing this for now, but we can keep discussing your use case here.

**Closed by tannerlinsley** 2019-12-02 16:50 UTC

**Comment by TJHdev** [comment] 2020-02-17 14:34
Hi there, I'm looking for the similar functionality. If there is any match within a base level and subRows it should return that whole branch, preferably with the matches expanded, non matches minimised. It allows the end user to see context of where the row sits.

**Comment by shellebelin** [comment] 2020-07-02 08:25
I am having the same problem, I would like to see subRows filtered and expanded from the right place. Any implementation ideas?

**Comment by shurshilov** [comment] 2022-10-12 08:28
Most likely the problem is that you use UseExpand and you need UseGroupBy check in the examples how filtering works in groups and expanded in general it's strange that it works differently, I would even say most likely this is an error that still remains. As I understand it, the combination of expand and filter is just rare, but still I have seen several articles on this topic.
