### ISSUE TITLE
Production version of v7.0.0 leaves empty cells

### ISSUE THREAD

**Issue by Sujatha-Pushparaj** [tannerlinsley/react-table#2041] opened 2020-03-23 08:10 UTC
With the v7.0.0 version of the react-table, it is working perfect in browser environment. But in production environment, it is not rendering the values inside cell properly. As a result most of the cells are empty in the production.

This problem is not there in v7.0.0-rc.16. But that version is holding a problem in row selection when the filter in enabled.

Is there any way (version) where both of these bugs are handled?

**Comment by ac1997** [comment] 2020-03-23 22:56
Duplicate of #1992

**Comment by tannerlinsley** [comment] 2020-04-01 22:32
Fixed!

**Closed by tannerlinsley** 2020-04-01 22:32 UTC
