### ISSUE TITLE
Moving from beta 13 to RC15 caused infinite looping while onFetchData 

### ISSUE THREAD

**Issue by chozze** [tannerlinsley/react-table#1904] opened 2020-02-13 15:47 UTC
I was using this code (a little bit more expanded), but basically this cause the table to fetch data in infinite loop after updating to RC15.

```
function Table({ data, onFetchData }) {
  const {
    state: { pageIndex, pageSize, sortBy, filters },
  } = useTable({
    data,
  })

  // When these table states change, fetch new data!
  React.useEffect(() => {
    onFetchData({ pageIndex, pageSize, sortBy, filters })
  }, [onFetchData, pageIndex, pageSize, sortBy, filters])

  return </>
}
```

**Comment by chozze** [comment] 2020-02-14 09:35
sandbox here, https://codesandbox.io/s/flamboyant-villani-7p0n3

**Comment by tannerlinsley** [comment] 2020-02-16 02:57
- If your `onFetchData` function isn't stable (doesn't have a React.useCallback around it), then that could be the cause.
- The sandbox you posted doesn't contain any of that code and seemingly works fine?

Closing for triage, but please open again with a sandbox and more info if this keeps happening.

**Closed by tannerlinsley** 2020-02-16 02:57 UTC

**Comment by chozze** [comment] 2020-02-17 09:10
Sorry, did not save the sandbox, please check it out now. 

'SortBy' or 'filters' are causing refresh of 'onFetchData' function - with or without a React.useCallback.

https://codesandbox.io/s/flamboyant-villani-7p0n3
