### ISSUE TITLE
v6.9.0 Major Regression Bugs

### ISSUE THREAD

**Issue by JayV30** [tannerlinsley/react-table#1243] opened 2019-02-01 16:10 UTC
I do not currently have time to investigate and do a proper bug report, but you pushed an update to v6.9.0 recently and then stated support for v6 is done. Well, today I installed v6.9.0 and column resizing in Chrome (didn't check other browsers) on Win10 broke. I can drag for a second, then the drag ends and locks the column size.

I reverted to 6.8.6 and the issue is gone. Just thought you should be aware that your 'final' v6 update potentially broke some functionality, at least for me.

**Comment by tannerlinsley** [comment] 2019-02-01 16:13
We definitely need to get this fixed then. Support for v6 isn't necessarily done, we're just not adding any new features. Mission critical bugs for v6 will still be taken care of and this is no exception. 

I'll take a look at the PR's we merged for this last version and pull up some potential candidates for what broke it.

**Comment by JayV30** [comment] 2019-02-01 16:15
Apologies, I misunderstood this continuing support for v6! Thanks for the reply. Love love love this project.

**Comment by tannerlinsley** [comment] 2019-02-01 16:17
Did I have any messaging anywhere that left you confused? I want to make sure I'm not giving that impression anywhere, but it's totally possible. I know I was really aggressive with closing issues yesterday (mostly to maintain sanity), so I'm expecting some amount of pushback.

**Comment by tannerlinsley** [comment] 2019-02-01 16:17
Here's the total changes from 6.8.6 to 6.9.0: https://github.com/tannerlinsley/react-table/compare/fcdc3d88bc8848ca18c66c9383f1772e5e28f8d1...v6

**Comment by ollierob** [comment] 2019-02-01 16:18
Possibly related but an ugprade to 6.9.0 also introduced the below, I'm happy enough not to upgrade for now but maybe it will help with the diagnosis:
```
column.getHeaderProps is not a function
    at makeHeaderGroup (index.js?d1e9:240)
    at Array.map (<anonymous>)
    at makeHeaderGroups (index.js?d1e9:286)
    at Array.map (<anonymous>)
    at makeTable (index.js?d1e9:764)
    at ReactTable.render (index.js?d1e9:797)
```

**Comment by tannerlinsley** [comment] 2019-02-01 16:20
@jonniedarko Any ideas here? You're recursive column work was the most intensive on this last version.

**Comment by JayV30** [comment] 2019-02-01 16:23
@tannerlinsley Sorry I can't recall what I read that lead me to believe there was no further support for v6. I know I skimmed something that caused that belief but now I can't find it. Sorry for spreading misinformation! You all were on this issue crazy fast. Regardless of the time it takes to resolve, thanks!

**Comment by stahlmanDesign** [comment] 2019-02-01 17:56
6.9.0 also broke subcomponents. The arrow to open a subcomponent is missing

**Comment by jonniedarko** [comment] 2019-02-01 18:20
> @jonniedarko Any ideas here? You're recursive column work was the most intensive on this last version.

I will look into it asap

**Comment by jonniedarko** [comment] 2019-02-01 19:02
@tannerlinsley I can confirm that My changes do seem to have caused the subcomponents issue and the resize issue. Feel free to revert my changes for now, I will work on a fix and get it in a PR asap

**Comment by jonniedarko** [comment] 2019-02-01 19:03
It is worth noting that the resize issue only seems to occur when using subcomponents

**Comment by ashrayber01** [comment] 2019-02-01 19:16
It seems that selection is broken as well, since react-table is now prepending it with 'select'. 

https://github.com/tannerlinsley/react-table/commit/de6389cafc627c55233bd184444883dab16de4d1

**Comment by austinbutler** [comment] 2019-02-01 23:52
Also getting `TypeError: Cannot assign to read only property 'value' of object '#<Object>'` after upgrading from 6.8.6 when changing a cell's row value. I don't know if this is a bug or an intended change, since there's no changelog that I can find for 6.9.0. If it's a bug I can open a new bug issue.

**Comment by tannerlinsley** [comment] 2019-02-03 19:03
#1244 is also another bug we found with this version.

**Comment by Petercopter** [comment] 2019-02-03 20:30
Heya! I noticed that open filter fields in column headers are losing focus after you keyup in 6.9.0.

Also I had a `Cell:` that didn't have a consistent return that tripped up 6.9.0 as well. Can't complain about that one though. 

Pretty sure you're on top of these, I'll keep an eye out for the updates and report back. Thanks for the hard work!

**Comment by visualcookie** [comment] 2019-02-05 08:14
6.9.0 also breaks rendering. Getting: `TypeError: visibleColumns is undefined`

**Comment by sagarrison12** [comment] 2019-02-05 14:31
Using the `column` prop on react-table with an object extending ReactTableDefaults.column and a new `Cell:` renderer is broken. Cell render method doesn't even get touched. Reverting back to 6.8.6 fixed the issue. Not sure if the other items were being honored from my override object. (headerClassName and style) . Workaround is to apply these things directly on the column definition themselves.

**Comment by tannerlinsley** [comment] 2019-02-05 18:04
I'll cut a release for the revert asap

**Comment by orangecoding** [comment] 2019-02-06 07:12
t might also help to have release notes for 6.9.0 :)

**Comment by AbhaysinghBhosale** [comment] 2019-02-07 05:22
> 6.9.0 also broke subcomponents. The arrow to open a subcomponent is missing

Same for me and i have reported the bug

**Comment by patelnav** [comment] 2019-02-07 05:36
@tannerlinsley: you mind cutting a v6.9.1 release that backtracks so we don't have to do package shenanigans until this stabilizes?

**Comment by tannerlinsley** [comment] 2019-02-07 17:01
Working on it

**Comment by tannerlinsley** [comment] 2019-02-11 16:37
6.9.1 is now release with the buggy PR reverted. Closing for now. Please reopen if issues continue.

**Closed by tannerlinsley** 2019-02-11 16:37 UTC
Labels: bug

**Comment by Android3000** [comment] 2019-02-11 20:36
Hi @tannerlinsley -- just updated to 6.9.1 from 6.8.6 and I'm still getting some new errors that were not present before:
```
Uncaught ReferenceError: i is not defined
    at makeHeaderGroups (index.js:274)
    at makeTable (index.js:764)
    at ReactTable.render (index.js:797)
```
I'm currently digging in to see what might be causing it so I can provide an example, but wanted to note this in case anything immediately jumped to mind that might be at fault...

Thanks!

**Comment by tannerlinsley** [comment] 2019-02-11 20:58
Seeing how the PR that we reverted was only a **part** of the total version bump, there could still be some bugs. Please submit a PR if you think you found one.

**Comment by Android3000** [comment] 2019-02-11 20:58
Sounds good. I'm going to try to find a reproducible scenario so I can post a code snippet with it as well. Thanks.

**Comment by berkaygurbuz** [comment] 2022-03-31 12:42
@sagarrison12 @tannerlinsley I was using headerClassName 6.8.6 now i bump packages in my project to 7.7.9. Some properties and some interfaces is like never born. I couldn't find anything about them like RowRenderProps, headerClassName Is there any changelog or migration guide ?
