### ISSUE TITLE
Columns resizing not working in 6.9.2

### ISSUE THREAD

**Issue by garajo** [tannerlinsley/react-table#1281] opened 2019-03-03 01:04 UTC
# Using v6?

v6 is now considered feature complete to its current abilities and limitations. We are not actively working to fix any issues for v6 any more. We will, however, merge any non-breaking pull requests submitted to fix anything in v6.

# Using v7?

Thanks for using the alpha version of React Table v7! We're very excited about it.

**Describe the bug**

I just upgraded from 6.8.6 to 6.9.2 four days ago. Yesterday I noticed that my column resizing wasn't working. Further debugging showed these values in onResizedEvent `{ resized: { value: NaN}}`. I reverted back to 6.8.6, and it worked again. 

**To Reproduce**
1. using 6.9.2, resize a column
2. review values of `onResizedEvent`, as described above.

**Expected behavior**
columns to resize correctly

**Codesandbox!**
Use a new [react-table codesandbox](https://codesandbox.io/s/m5lxzzpz69) to reproduce the issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] Version 72.0.3626.119

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by daothithientamm** [comment] 2019-03-04 09:12
remember set id for columns. Columns resizing will be working.
Ex: 
const columns = [
 {
                **id:"name",**
                Header: "Name",
                accessor: "Name",
                width: 150,
            },
            {
                **id:"email",**
                Header: "Email",
                accessor: "Email",
            },
];

**Comment by dbertella** [comment] 2019-03-04 12:50
@daothithientamm why? if I can ask? did it change in a latest release?

**Comment by tannerlinsley** [comment] 2019-03-04 15:38
It's a regression bug. Two unrelated PR's were merged with conflicting code changes that we are still working out.

**Comment by dbertella** [comment] 2019-03-04 16:40
Cool thank you for letting me know, there is another bug I believe I discovered in one of the latest version and is about using `Cell: ({ value }) => value && <MyCustomComponent value={value} />` it was working before and it failed badly after latest update. I believe I'll be sticking on the 6.8.x version for now before to switch to 7. Thanks again for the awesome job here!

**Comment by SourceCipher** [comment] 2019-03-05 12:23
@daothithientamm its not . We suddenly experienced this issue without any upgrades to the table. Adding unique id values for each column wont help. We using this component in a lot of pages and its now not working in all of them the resizing of the headers..

**Comment by Mujaddadi** [comment] 2019-03-05 13:41
I have a similar but weird issue. The last column is resizing properly but remaining ones are not.

**Comment by dbertella** [comment] 2019-03-05 14:11
guys fix the dependency in package json, `"react-table": "6.8.6",` work just fine, didn't try anything else

**Comment by SourceCipher** [comment] 2019-03-05 14:22
@dbertella How funny it is.. I just fixed by doing the same thing like a min ago! The problem for us was that we had `^6.8.6` and by removing ^ to `6.8.6` solved the problem!

**Comment by alturium** [comment] 2019-03-08 22:49
Thanks @dbertella  and @SourceCipher !  I can't believe changing from ^6.8.6 to 6.8.6 in the package.json worked!  I've spent hours trying to figure out what the problem was.  Any insight why this would fix the problem???

**Comment by dbertella** [comment] 2019-03-09 21:45
well this is not fixing the problem this means freeze the dependency to that particular version and forget to update it. Version 6.9.x seems to have some bug or at least it seems to work differently since the previous version and since react-table 6.x is no longer supported by its maintainers there is no point in updating it right now, I guess we will have to wait for the next major release v7 and update our codebase or stick with this version.

**Comment by PatrikKoskenniemi** [comment] 2019-04-11 11:23
Hi Guys!
I needed this version to work since there is a bug in 6.8.6 which doesn't let me use pivotBy at the same time as a column is editable.
What I can see the reason for this behavior is that minResizeWidth is undefined when passed to a Math.max() which returns NaN.

So a workaround that works for me is to set minResizeWidth to a value for each column I need to resize.

Example:
const columns = [
{
id:"name",
Header: "Name",
accessor: "Name",
**minResizeWidth: 150**,
},
{
id:"email",
Header: "Email",
accessor: "Email",
**minResizeWidth: 1**,
},
];

**Comment by tannerlinsley** [comment] 2019-04-23 21:50
The best solution for this we have right now is to pin to version 6.8.6. I this is not optimal, but it's the best we can do right now until v7 is released.

**Closed by tannerlinsley** 2019-04-23 21:50 UTC

**Comment by stahlmanDesign** [comment] 2019-04-24 16:12
This seems to be fixed in v6.10.0

**Comment by QuantumInformation** [comment] 2019-04-25 12:34
6.10 fixes it for me, great work
