### ISSUE TITLE
Example of 100k row aggregation is broken

### ISSUE THREAD

**Issue by geekysrm** [tannerlinsley/react-table#1304] opened 2019-03-30 08:45 UTC
The demo https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation
is broken.

Error shown:
```
Potential infinite loop: exceeded 10001 iterations. You can disable this check by creating a sandbox.config.json file.
```

**Comment by vijaybritto** [comment] 2019-04-01 08:51
duplicate of #932

**Comment by kreja** [comment] 2019-04-09 09:49
This example has a `sandbox.config.json`, but it is under /src, you can drag it to the root directory, then you'll see the demo works perfectly.

**Comment by tannerlinsley** [comment] 2019-04-23 21:41
The sandbox.config.js has been moved to the root of the project. Thanks.

**Closed by tannerlinsley** 2019-04-23 21:41 UTC

**Comment by togakangaroo** [comment] 2019-04-28 14:47
@tannerlinsley the problem is that the file needs to be named `sadnbox.config.json` and the [pull request](https://github.com/tannerlinsley/react-table/pull/1283) not only moved it but also renamed it to a `.js` file . (I'm not even sure it is a valid js file, though its simple structure might coincidentally be the same as using js blocks+labels so it might pass a very very loose linter)

**Comment by tannerlinsley** [comment] 2019-04-28 15:21
Could you open a PR to apply those changes?

Tanner Linsley

**Comment by togakangaroo** [comment] 2019-04-28 15:35
[Done](https://github.com/tannerlinsley/react-table/pull/1323) 

I thought I'd done it already but I PRed into my own fork...doh
