### ISSUE TITLE
Kitchen Sink Freezes

### ISSUE THREAD

**Issue by mrchess** [tannerlinsley/react-table#1661] opened 2019-11-26 01:06 UTC
**Describe the bug**
Navigating to the kitchen sink: https://gw0ih.csb.app/ and clicking on the fist emoji freezes the entire table -- you cannot use or click on any of the table after you click on the fist emoji.

**To Reproduce**

1. Go to https://gw0ih.csb.app/
2. Click the "Fist👊"  emoji next to **Status**
3. See error:
```
proxyConsole.js:64 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in Table (at App.js:622)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div (at App.js:620)
    in App (at src/index.js:7)
```

**Expected behavior**
Table is still usable

**Actual Behavior**
Table is frozen. Site is frozen.

**Desktop (please complete the following information):**

- OS: Mojave 10.14.6
- Browser: Chrome
- Version: Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by iamjon** [comment] 2019-11-27 06:57
This seems to be a duplicate of https://github.com/tannerlinsley/react-table/issues/1657

**Comment by tannerlinsley** [comment] 2019-12-01 06:45
This is fixed in the latest version

**Closed by tannerlinsley** 2019-12-01 06:45 UTC
