### ISSUE TITLE
Empty page is rendered when data set is reduced when using filters

### ISSUE THREAD

**Issue by aezumezu** [tannerlinsley/react-table#159] opened 2017-03-30 17:01 UTC
## Problem Description
Page renders correctly until the data supplied is reduced when using filters. This results in the pagination saying `Page 2 of 1`. And renders nothing on the current page until previous button is clicked.

Image from when data set is complete
![page 2 0f 2](https://cloud.githubusercontent.com/assets/17248267/24516488/bef76e7e-1572-11e7-8b2c-476858c11264.png)

When data set is filtered
![error](https://cloud.githubusercontent.com/assets/17248267/24516502/d358a55e-1572-11e7-8309-d60cf975e928.png)

## Code snippet
```
    const filteredList = filterStudents(students, filterItems);
    return (
      <div>
        {this.searchField()}
        <ReactTable
          data={filteredList}
          columns={columns}
          className="-striped -highlight"
        />
      </div>
```

On first load, filterItems is an empty object so it returns the whole data. Later when it has items to filter the list by, the content of the data becomes smaller resulting in the error above.

**Comment by TacticalCoding** [comment] 2017-03-30 17:05
Can you get it to happen on the demo page?

https://react-table.js.org/?selectedKind=2.%20Demos&selectedStory=Custom%20Filtering&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

I can't seem to reproduce it.

**Comment by aezumezu** [comment] 2017-03-30 17:07
Okay will try it.

**Comment by TacticalCoding** [comment] 2017-03-30 17:11
Oh I thought you meant using the build in filters that were just added.

**Comment by aezumezu** [comment] 2017-03-30 17:51
I've taken a look at the built-in filters. Correct me if i'm wrong, but it seems to filter based on the content of the column. This situation will not serve my purpose as the conditions my filters are based on are not rendered on the the table and can't be reached by the column accessors.

**Comment by TacticalCoding** [comment] 2017-03-30 17:58
By default it does filter on the content of the column, but you can override the column's filter method and in theory have it use data from outside of just the table row.

The way you originally were doing it should also work, so if there is a bug doing it that way it should be fixed.

**Comment by aezumezu** [comment] 2017-03-30 19:28
Okay.
So i tried placing the filter on the column
```
        columns: [{
          accessor: 'name',
          sortable: false,
          render: props => <span>{props.value}</span>,
          minWidth: 150,
          sort: 'asc',
          filterMethod: () => filterClients(this.props.clients, this.props.filterOptions),
        }],
```
And again on the ReactTable component 
```
        <ReactTable
          data={this.state.searchData}
          columns={columns}
          className="-striped -highlight"
          onTrClick={row => (window.location.href = `${Paths.CLIENT_DETAILS_URL}/${row.id}`)}
        />
```
Both methods behaved exactly like the first instance. It filtered the array, but the pagination didn't sync.

I was able to get the behaviour i wanted by modifying the componentWillReceiveProps method in the pagination file to be
```
  componentWillReceiveProps(nextProps) {
    this.setState({ page: nextProps.page }, () => {
      const page = this.state.page;
      const pages = this.props.pages;
      if (page !== 0 && page >= pages) {
        this.changePage(1);
      };
    })
  },
```

See if this check can be implemented.

**Comment by tannerlinsley** [comment] 2017-03-30 20:08
@TacticalCoding How does that look to you? There weren't many changes in the pagination component from the filtering PR, so we should probably consider this or something akin to it.

**Comment by TacticalCoding** [comment] 2017-03-30 20:40
Isn't this line supposed to be doing something about going past the page size? I think it has a bug:
https://github.com/tannerlinsley/react-table/blob/master/src/methods.js#L218

Shouldn't that be `newPages - 1` and not `newPage - 1` since newPage isn't defined anywhere yet?

Can someone test to see if that fixes the issue?

**Comment by aezumezu** [comment] 2017-03-30 20:45
I just checked. It didn't handle it.

**Comment by TacticalCoding** [comment] 2017-03-30 22:01
I'm not sure if you're building the library yourself but if you are you can try my fork and see if that is acceptable.
https://github.com/TacticalCoding/react-table

The changes made can be found in the PR:
https://github.com/tannerlinsley/react-table/pull/160/files

**Comment by aezumezu** [comment] 2017-03-30 22:31
Awesome! Your fork works. https://github.com/TacticalCoding/react-table.git

Yes to your earlier thought. I was building the library.

How soon will it be available in the main package?

**Closed** 2017-03-30 23:02 UTC

**Comment by tannerlinsley** [comment] 2017-03-30 23:04
It's now available in 5.4.1

**Comment by Karuhanga** [comment] 2019-07-06 13:32
Hey @tannerlinsley,

Apologies for dredging out an old issue, but setting the page to the last one available instead of the first one available when data changes looks like an odd default. Rationale?

**Comment by Japhetism** [comment] 2020-01-08 13:26
This worked for me, control your page manually
` page={this.props.startPage ? this.props.startPage - 1 : this.state.page}
        onFetchData={(state, instance) => {
            this.setState({page: state.page})
          }}`
Always set this.props.startPage to be null when the next button is clicked
