### ISSUE TITLE
useRowSelect does not work as expected with CRA strict mode

### ISSUE THREAD

**Issue by gopinav** [tannerlinsley/react-table#2659] opened 2020-08-21 06:34 UTC
Hello, this is not a react-table issue itself perhaps but one I'd like to bring to the attention of the community  if it already hasn't been.

**Issue**
Rows do not get selected as you would expect with StrictMode in CRA.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/infallible-sara-6whim?file=/src/index.js

**Steps To Reproduce (required)**
Try selecting multiple rows. They don't get selected as you'd expect.

**Expected behavior (Recommended)**
Should behave as it would in the example provided in the docs.
If not, I highly recommend a warning message of sorts that the user should disable StrictMode

**Current Workaround**
Remove StrictMode. ( Doesn't affect production builds to begin with but causes the issue during dev)
![image](https://user-images.githubusercontent.com/13146172/90859723-5cd8a680-e3a6-11ea-9be2-389c13200460.png)

**Comment by centrodph** [comment] 2020-08-24 00:47
@gopinav I was able to reproduce this issue. I think I found the cause of the issue.

<img width="1222" alt="Screen Shot 2020-08-23 at 21 43 30" src="https://user-images.githubusercontent.com/2073951/90993118-01ffa480-e58a-11ea-9fd3-5837cbf8a117.png">


Basically I am using the reducer state as source of true.

**Comment by javonclarke** [comment] 2020-09-09 03:59
This helped me solve my issue with selection.

**Comment by Ricka7x** [comment] 2020-09-23 18:49
Spent a whole day trying to figure out if I was doing anything wrong, and turns out I wasn't thanks @gopinav

**Comment by tannerlinsley** [comment] 2020-10-05 03:39
This should be fixed now.

**Closed by tannerlinsley** 2020-10-05 03:39 UTC
