### ISSUE TITLE
Sub rows disappear after global filter

### ISSUE THREAD

**Issue by bmcgary** [tannerlinsley/react-table#2241] opened 2020-04-27 21:23 UTC
First off, thanks for the great lib. I have been impressed at how easy it is to drop this in and use it (with your own UI). Easily in the top 5 best JS libs I have ever used.

**Describe the bug (required)**
A row can be expanded, showing the sub rows. When a row is filtered using globalFilter the subrow is removed and never seen again, even after the filter has been cleared. The subRows is still in "data", but it's no longer in "rows". 

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/serene-chebyshev-80wsi?file=/src/App.js

**Steps To Reproduce (required)**

1. Use the input to filter a specific row.
2. The expand hand is now gone.
3. Clear the filter
4. The expand hand is _still_ gone.

**Expected behavior (Recommended)**
When the filter is removed the sub row should reappear.
(I can see the sub rows being filtered out based on the query, but after the query is cleared the sub rows should come back)

**Screenshots**
![react table expand global filter issue](https://user-images.githubusercontent.com/9909710/80420902-66d31880-8890-11ea-8c2c-aa7f69f5dde1.gif)

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: 
-- Chrome (v81.0.4044.122 (Official Build) (64-bit)); 
-- FF (v75.0)

**Smartphone (please complete the following information):**
Not tested

**Additional context**
using v7, in case that wasn't obvious. 

I did do some light digging and it appears in useGlobalFilter.js:138-140 it filters the rows and sets row.subRow to that result. When the filter is removed the row.subRow is still an empty array; it doesn't get reverted back to what is in data. 🤷‍♂️

**Comment by govi74** [comment] 2020-05-03 23:15
Duplicate of https://github.com/tannerlinsley/react-table/issues/2064

**Closed** 2020-05-05 16:46 UTC
