### ISSUE TITLE
column.getSortByToggleProps is not a function

### ISSUE THREAD

**Issue by dtfraighter** [tannerlinsley/react-table#1481] opened 2019-08-28 00:25 UTC
# Using v6? No

# Using v7? Yes

**Describe the bug**
When trying to use the return value of column.getSortByToggleProps as an argument to column.getHeadProps(), a Type error occurs stating that `column.getSortByToggleProps is not a function`

**Expected behavior**
The function should be a property of column, since it is being used in some of the examples. 

**Screenshots**
<img width="656" alt="Screen Shot 2019-08-27 at 7 23 59 PM" src="https://user-images.githubusercontent.com/47991566/63817065-3ea9a900-c900-11e9-8e59-4c94ed336994.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 10.14.5

**Comment by dtfraighter** [comment] 2019-08-28 21:42
Unfortunately I cannot. The code is proprietary and to take a small chunk out wouldn’t work because the code relies on other things in our repo.

**Comment by tannerlinsley** [comment] 2019-08-28 21:45
I would focus then on not using any of your code and just tweaking one of the examples in codesandbox to demonstrate the bug. If I can't reproduce it, then I don't know how to fix it.

**Comment by tannerlinsley** [comment] 2019-08-30 14:06
Closing this for triage. Please reopen a new issue if/when you have more information on how to replicate the problem.

Thanks!

**Closed by tannerlinsley** 2019-08-30 14:06 UTC

**Comment by dtfraighter** [comment] 2019-08-30 15:41
@tannerlinsley - My boss helped me find the problem. It was the ... in front of the getSortByToggleProps. Didn't mean to put that there!

**Comment by dtfraighter** [comment] 2019-08-30 19:55
Hey Tanner, I figured out the issue. I wasn't included the useSortBy inside of the useTable hook.

**Comment by Hadard753** [comment] 2019-12-30 14:46
Hi same issue happens to me,, I am trying to implement a table which combine few features (paging, sorting, row select etc.) so far it is all works except when I try to integrate the sort feature I cant call column.getSortByToggleProps() if I do that the code breaks

here is a link to codeSandbox where I played with the example in the official API: 
https://codesandbox.io/s/laughing-bose-6pihp?fontsize=14&hidenavigation=1&theme=dark
you can take a look at row 149-150 in App.js

**Comment by mcalixte** [comment] 2020-12-11 15:29
I know this is old, however I am getting the exact same error and I have actually included the useSortBy inside of the useTable hook. 

I get "Property 'getSortByToggleProps' does not exist on type 'HeaderGroup<object>'"

This prop remains hidden even after having used the useSortBy hook. Is there a solution for this.

<img width="984" alt="Screen Shot 2020-12-11 at 10 27 46 AM" src="https://user-images.githubusercontent.com/25334458/101922055-ab02f700-3b9b-11eb-9750-25be278857f8.png">

**Comment by JulesBlm** [comment] 2020-12-23 10:38
I ran into the same issue but noticed that I had simply misplaced `useSortBy` like this

  ```javascript
  useTable(
  {
    columns,
    data,
    useSortBy, // 🚨 useSortBy inside the options object will lead to "Property 'getSortByToggleProps' does not exist on type 'HeaderGroup'"
  }
);
  ```

  ```javascript
  useTable(
  {
    columns,
    data,
  }
  useSortBy, // ✅  useSortBy placed after the options object
  );
  ```
  
  Hope this helps.

**Comment by Rajiv074** [comment] 2021-02-07 07:11
import {useTable,useSortBy} from 'react-table';
const tableinstance =  useTable({             
        columns:columns,
        data:data
    },useSortBy)
this works for me

**Comment by EmmaB** [comment] 2022-03-26 09:37
Thought I'd share the stupid thing I did which threw this error for me. Mindlessly destructured `useSortBy` from React, not react-table.

obviously don't do this:
```
import React, { useMemo, useEffect, useState, useRef, useSortBy } from "react"
import { useTable } from "react-table"
```

do this: 
```
import React, { useMemo, useEffect, useState, useRef } from "react"
import { useTable, useSortBy } from "react-table"
```

**Comment by GunB** [comment] 2022-04-28 23:54
Sorry for reopening this issue but I'm facing teh same problem. 
https://gist.github.com/GunB/73d32ff41992e434aee2f50c1d5a4756
I'm using "react-table": "^7.7.0" with typescript. Using "@types/react-table": "^7.7.11" to reach the types needed.
Am I doing something wrong? I'm new to this library

```
const columnsMemo: Array<Column<T extends object ? any : any>> = useMemo(() => [...columns], []);
const dataMemo: Array<T extends object ? any : any> = useMemo(() => [...data], []);

    const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } = useTable(
        {
            columns: columnsMemo,
            data: dataMemo,
        },
        useSortBy,
    );
```
![image](https://user-images.githubusercontent.com/3722960/165865447-e8e4e29e-d847-49c6-96cc-257257cb9145.png)

And if I use the soltion given at https://github.com/TanStack/react-table/issues/2970#issuecomment-756364081 then this happens...

![image](https://user-images.githubusercontent.com/3722960/165865583-c4848f26-2742-496d-adab-f316a0962008.png)

**Comment by jmohit2104** [comment] 2022-05-01 10:33
> Sorry for reopening this issue but I'm facing teh same problem. https://gist.github.com/GunB/73d32ff41992e434aee2f50c1d5a4756 I'm using "react-table": "^7.7.0" with typescript. Using "@types/react-table": "^7.7.11" to reach the types needed. Am I doing something wrong? I'm new to this library
> 
> ```
> const columnsMemo: Array<Column<T extends object ? any : any>> = useMemo(() => [...columns], []);
> const dataMemo: Array<T extends object ? any : any> = useMemo(() => [...data], []);
> 
>     const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } = useTable(
>         {
>             columns: columnsMemo,
>             data: dataMemo,
>         },
>         useSortBy,
>     );
> ```
> 
> ![image](https://user-images.githubusercontent.com/3722960/165865447-e8e4e29e-d847-49c6-96cc-257257cb9145.png)
> 
> And if I use the soltion given at [#2970 (comment)](https://github.com/TanStack/react-table/issues/2970#issuecomment-756364081) then this happens...
> 
> ![image](https://user-images.githubusercontent.com/3722960/165865583-c4848f26-2742-496d-adab-f316a0962008.png)

I am getting the same error.

**Comment by suraj-kawale-au2** [comment] 2022-05-13 23:16
Same issue , getSortByToggleProps is not available in column . In my case I have used useSortBy as recommended on docs 
![image](https://user-images.githubusercontent.com/13823258/168400333-fd1f9827-1863-484b-b7d1-de6544a24bf5.png)

**Comment by subhamg** [comment] 2022-05-14 11:18
> > Sorry for reopening this issue but I'm facing teh same problem. https://gist.github.com/GunB/73d32ff41992e434aee2f50c1d5a4756 I'm using "react-table": "^7.7.0" with typescript. Using "@types/react-table": "^7.7.11" to reach the types needed. Am I doing something wrong? I'm new to this library
> > ```
> > const columnsMemo: Array<Column<T extends object ? any : any>> = useMemo(() => [...columns], []);
> > const dataMemo: Array<T extends object ? any : any> = useMemo(() => [...data], []);
> > 
> >     const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } = useTable(
> >         {
> >             columns: columnsMemo,
> >             data: dataMemo,
> >         },
> >         useSortBy,
> >     );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/3722960/165865447-e8e4e29e-d847-49c6-96cc-257257cb9145.png)
> > And if I use the soltion given at [#2970 (comment)](https://github.com/TanStack/react-table/issues/2970#issuecomment-756364081) then this happens...
> > ![image](https://user-images.githubusercontent.com/3722960/165865583-c4848f26-2742-496d-adab-f316a0962008.png)
> 
> I am getting the same error.

A workaround would be to change the interface of column to **any**. 

```
<thead>
{headerGroups.map((headerGroup) => (
  <tr
    {...headerGroup.getHeaderGroupProps()}
  >
    {headerGroup.headers.map((column: any) => (
      <th
        {...column.getHeaderProps(
          column.getSortByToggleProps()
        )}
      >
        {column.render('Header')}
      </th>
    ))}
  </tr>
))}
</thead>
```

**Comment by js-pankaj-rana** [comment] 2022-05-29 05:15
I worked on react-table 7.8.0 and was facing the same issue: column.getSortByToggleProps() is not function of HeaderGroup.
But I resolved it using below code, and it works in correct order. 

`
 <thead>
          {headerGroups.map(headerGroup => (
            <tr {...headerGroup.getHeaderGroupProps()}>
              <th>#</th>
              {headerGroup.headers.map((column: **any** ) => (
                <th {...column.getHeaderProps( column.getSortByToggleProps() )}>
                  {column.render('Header')}
                  {column.isSorted ? (column.isSortedDesc ? "sss": "ttt") : '' }
                </th>
              ))}
            </tr>
          ))}
        </thead>
`

**Comment by tanvibhakta** [comment] 2022-08-11 03:30
>  ```headerGroup.headers.map((column: any ) => ()```

So basically the acceptable fix for this incompatibility with types is to force the compiler to ignore them? That doesn't sound like a good idea.

**Comment by BrenoAlexandre** [comment] 2023-02-01 19:53
Anyone found a proper fix for this issue?

**Comment by paulvan2000** [comment] 2023-03-15 01:57
having the same issue now, any fix?

**Comment by ChinmayGopal931** [comment] 2023-03-22 06:51
Facing the same issue.

**Comment by WorkAccVikas** [comment] 2023-12-27 15:55
It works for me.

- Create react-table-config.d.ts file in src folder.
    - Add code of react-table-config.d.ts in react-table (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table)
